### ISSUE TITLE
.epub file crashes on snap install

### ISSUE THREAD

**Issue by thraizz** [burtonator/polar-bookshelf#1427]
**Description**
Opening an `.epub` document fails.

**To Reproduce**
1. Install polar from snap
2. Open any `.epub` from disk
3. The reader tries to open the file and crashes

**Expected behavior**
The reader should be able to open `.epub` files.

**Screenshots**
```
FIXME: docMetaFileRef:  
Object
docFile:
    hashcode: undefined
    name: undefined
__proto__: Object
    docInfo: DocInfo
    added: "2020-06-20T14:14:52.255Z"
    archived: false
    attachments: {}
    filename: undefined
    fingerprint: "0x0001"
    flagged: false
    nrPages: 0
    pagemarkType: "SINGLE_COLUMN"
    progress: 0
     properties: {}
    tags: {}
    uuid: "z2020-06-20T14:14:52.256Z+000000-820386329529"
    __proto__: SerializedObject
     fingerprint: "0x0001"
     __proto__: Object
/snap/polar-bookshel…ConsoleLogger.js:26 [error] [1.100.13] Failed to trigger:  Error: Precondition (argument) for 'docFile.name' failed: undefined
    at Function.assertPresent (:8500/snap/polar-boo…Preconditions.js:72)
    at getURL (:8500/snap/polar-boo…ub/EPUBViewer.js:46)
    at EPUBViewer.start (:8500/snap/polar-boo…ub/EPUBViewer.js:50)
    at Launcher.<anonymous> (:8500/snap/polar-boo…apps/Launcher.js:58)
    at Generator.next (<anonymous>)
    at fulfilled (:8500/snap/polar-boo…/apps/Launcher.js:5)
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, Kernel 5.4.44
 - Browser: does not apply, electron app (or chromium I guess)
 - Version 1.100.13
